export default [
  {
    link: 'produto.html',
    image: '/images/product1.jpg',
    name: 'Lorem ipsum sit amet consectetur adipiscing elit sed do eiusmod tempor incidi...',
    discount: '-99%',
    brand: 'Marca',
    ref: 'Ref.: 000000000',
    oldPrice: 'R$ 999,99',
    price: 'R$ 888,88',
    installments: '12x de R$ 99,99 s/juros',
    categoryLink: '#',
    category: '+ categoria lorem ipsum',
  },
  {
    link: 'produto.html',
    image: '/images/product2.jpg',
    name: 'Lorem ipsum sit amet consectetur adipiscing elit sed do eiusmod tempor incidi...',
    discount: '-99%',
    brand: 'Marca',
    ref: 'Ref.: 000000000',
    oldPrice: 'R$ 999,99',
    price: 'R$ 888,88',
    installments: '12x de R$ 99,99 s/juros',
    categoryLink: '#',
    category: '+ categoria lorem ipsum',
  },
  {
    link: 'produto.html',
    image: '/images/product3.jpg',
    name: 'Lorem ipsum sit amet consectetur adipiscing elit sed do eiusmod tempor incidi...',
    discount: '-99%',
    brand: 'Marca',
    ref: 'Ref.: 000000000',
    oldPrice: 'R$ 999,99',
    price: 'R$ 888,88',
    installments: '12x de R$ 99,99 s/juros',
    categoryLink: '#',
    category: '+ categoria lorem ipsum',
  },
  {
    link: 'produto.html',
    image: '/images/product4.jpg',
    name: 'Lorem ipsum sit amet consectetur adipiscing elit sed do eiusmod tempor incidi...',
    discount: '-99%',
    brand: 'Marca',
    ref: 'Ref.: 000000000',
    oldPrice: 'R$ 999,99',
    price: 'R$ 888,88',
    installments: '12x de R$ 99,99 s/juros',
    categoryLink: '#',
    category: '+ categoria lorem ipsum',
  },
  {
    link: 'produto.html',
    image: '/images/product5.jpg',
    name: 'Lorem ipsum sit amet consectetur adipiscing elit sed do eiusmod tempor incidi...',
    discount: '-99%',
    brand: 'Marca',
    ref: 'Ref.: 000000000',
    oldPrice: 'R$ 999,99',
    price: 'R$ 888,88',
    installments: '12x de R$ 99,99 s/juros',
    categoryLink: '#',
    category: '+ categoria lorem ipsum',
  },
  {
    link: 'produto.html',
    image: '/images/product1.jpg',
    name: 'Lorem ipsum sit amet consectetur adipiscing elit sed do eiusmod tempor incidi...',
    discount: '-99%',
    brand: 'Marca',
    ref: 'Ref.: 000000000',
    oldPrice: 'R$ 999,99',
    price: 'R$ 888,88',
    installments: '12x de R$ 99,99 s/juros',
    categoryLink: '#',
    category: '+ categoria lorem ipsum',
  },
];
